//
// Created by lisy on 01.04.13.
//
// To change the template use AppCode | Preferences | File Templates.
//


#import "PYGSymbolConcepts.h"
#import "PYGCodeNameRefer.h"


static NSDictionary * symbolsOfConcepts = nil;

@implementation PYGSymbolConcepts {

}
+ (PYGCodeNameRefer *)codeRef:(NSUInteger)code {
    [self loadSymbols];
    if (symbolsOfConcepts != nil)
    {
        return [symbolsOfConcepts objectForKey:[NSNumber numberWithUnsignedInt:code]];
    }
    return nil;
}
+ (void) loadSymbols {
    if (symbolsOfConcepts == nil)
    {
        symbolsOfConcepts = [NSDictionary dictionaryWithObjectsAndKeys:
            CODE_NAME_REF(CONCEPT_UNKNOWN              , @"CONCEPT_UNKNOWN"),
            CODE_NAME_REF(CONCEPT_SALARY_MONTHLY       , @"CONCEPT_SALARY_MONTHLY"),
            CODE_NAME_REF(CONCEPT_SCHEDULE_WEEKLY      , @"CONCEPT_SCHEDULE_WEEKLY"),
            CODE_NAME_REF(CONCEPT_SCHEDULE_TERM        , @"CONCEPT_SCHEDULE_TERM"),
            CODE_NAME_REF(CONCEPT_TIMESHEET_PERIOD     , @"CONCEPT_TIMESHEET_PERIOD"),
            CODE_NAME_REF(CONCEPT_TIMESHEET_WORK       , @"CONCEPT_TIMESHEET_WORK"),
            CODE_NAME_REF(CONCEPT_HOURS_WORKING        , @"CONCEPT_HOURS_WORKING"),
            CODE_NAME_REF(CONCEPT_HOURS_ABSENCE        , @"CONCEPT_HOURS_ABSENCE"),
            CODE_NAME_REF(CONCEPT_TAX_INCOME_BASE      , @"CONCEPT_TAX_INCOME_BASE"),
            CODE_NAME_REF(CONCEPT_INSURANCE_HEALTH_BASE, @"CONCEPT_INSURANCE_HEALTH_BASE"),
            CODE_NAME_REF(CONCEPT_INSURANCE_SOCIAL_BASE, @"CONCEPT_INSURANCE_SOCIAL_BASE"),
            CODE_NAME_REF(CONCEPT_INSURANCE_HEALTH     , @"CONCEPT_INSURANCE_HEALTH"),
            CODE_NAME_REF(CONCEPT_INSURANCE_SOCIAL     , @"CONCEPT_INSURANCE_SOCIAL"),
            CODE_NAME_REF(CONCEPT_SAVINGS_PENSIONS     , @"CONCEPT_SAVINGS_PENSIONS"),
            CODE_NAME_REF(CONCEPT_TAX_EMPLOYERS_HEALTH , @"CONCEPT_TAX_EMPLOYERS_HEALTH"),
            CODE_NAME_REF(CONCEPT_TAX_EMPLOYERS_SOCIAL , @"CONCEPT_TAX_EMPLOYERS_SOCIAL"),
            CODE_NAME_REF(CONCEPT_TAX_CLAIM_PAYER      , @"CONCEPT_TAX_CLAIM_PAYER"),
            CODE_NAME_REF(CONCEPT_TAX_CLAIM_DISABILITY , @"CONCEPT_TAX_CLAIM_DISABILITY"),
            CODE_NAME_REF(CONCEPT_TAX_CLAIM_STUDYING   , @"CONCEPT_TAX_CLAIM_STUDYING"),
            CODE_NAME_REF(CONCEPT_TAX_CLAIM_CHILD      , @"CONCEPT_TAX_CLAIM_CHILD"),
            CODE_NAME_REF(CONCEPT_TAX_ADVANCE_BASE     , @"CONCEPT_TAX_ADVANCE_BASE"),
            CODE_NAME_REF(CONCEPT_TAX_ADVANCE          , @"CONCEPT_TAX_ADVANCE"),
            CODE_NAME_REF(CONCEPT_TAX_RELIEF_PAYER     , @"CONCEPT_TAX_RELIEF_PAYER"),
            CODE_NAME_REF(CONCEPT_TAX_RELIEF_DISABILITY, @"CONCEPT_TAX_RELIEF_DISABILITY"),
            CODE_NAME_REF(CONCEPT_TAX_RELIEF_STUDYING  , @"CONCEPT_TAX_RELIEF_STUDYING"),
            CODE_NAME_REF(CONCEPT_TAX_RELIEF_CHILD     , @"CONCEPT_TAX_RELIEF_CHILD"),
            CODE_NAME_REF(CONCEPT_TAX_BONUS_CHILD      , @"CONCEPT_TAX_BONUS_CHILD"),
            CODE_NAME_REF(CONCEPT_TAX_ADVANCE_FINAL    , @"CONCEPT_TAX_ADVANCE_FINAL"),
            CODE_NAME_REF(CONCEPT_TAX_WITHHOLD_BASE    , @"CONCEPT_TAX_WITHHOLD_BASE"),
            CODE_NAME_REF(CONCEPT_TAX_WITHHOLD         , @"CONCEPT_TAX_WITHHOLD"),
            CODE_NAME_REF(CONCEPT_INCOME_GROSS         , @"CONCEPT_INCOME_GROSS"),
            CODE_NAME_REF(CONCEPT_INCOME_NETTO         , @"CONCEPT_INCOME_NETTO"), nil];
    }
}

@end

